version: '3.8'
volumes:
  redis-data:

services:
  websocket:
    platform: linux/amd64
    image: websocket:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: websocket
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - 8080
    ports:
      - "8080:80"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - websocket
